version: '3.7'

services:
  #Postgres
  db:
    image: postgres:latest
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env
    ports:
      - '5432:5432'
    # Make sure log colors show up correctly
    tty: true

volumes:
  data:
